//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RebarSketch {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RebarSketch.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the settings, set default.
        /// </summary>
        public static string ErrorFailedToLoadSettings {
            get {
                return ResourceManager.GetString("ErrorFailedToLoadSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string ErrorFileNotFound {
            get {
                return ResourceManager.GetString("ErrorFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder not found.
        /// </summary>
        public static string ErrorFolderNotFound {
            get {
                return ResourceManager.GetString("ErrorFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The library is not updated to the new XML format. Please launch the Sketch editor ot ask your BIM specialist for help..
        /// </summary>
        public static string ErrorLibraryOldVersion {
            get {
                return ResourceManager.GetString("ErrorLibraryOldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to handle elements. Maybe there are families that are not prescribed in the library. Families name:.
        /// </summary>
        public static string ErrorNoFamiliesInLibrary {
            get {
                return ResourceManager.GetString("ErrorNoFamiliesInLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the file, check user permissions.
        /// </summary>
        public static string ErrorNoPermission {
            get {
                return ResourceManager.GetString("ErrorNoPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable length rebars without Mark parameter are found. Please set the same Mark to the rebars that should be grouped..
        /// </summary>
        public static string ErrorRebarVariableLengthNoMark {
            get {
                return ResourceManager.GetString("ErrorRebarVariableLengthNoMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for rebar.
        /// </summary>
        public static string ForRebar {
            get {
                return ResourceManager.GetString("ForRebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameter type.
        /// </summary>
        public static string IncorrectParameterType {
            get {
                return ResourceManager.GetString("IncorrectParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe you should update the family.
        /// </summary>
        public static string MaybeUpdateFamily {
            get {
                return ResourceManager.GetString("MaybeUpdateFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The library is empty.
        /// </summary>
        public static string MessageEmptyLibrary {
            get {
                return ResourceManager.GetString("MessageEmptyLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sketch library will be updated to a new format.
        /// </summary>
        public static string MessageLibraryWillBeUpdated {
            get {
                return ResourceManager.GetString("MessageLibraryWillBeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please open a Sketch schedule, select all the rows and then launch this plugin!.
        /// </summary>
        public static string MessageNoSelectedRows {
            get {
                return ResourceManager.GetString("MessageNoSelectedRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 1 sketch subtype.
        /// </summary>
        public static string MoreOneSubtype {
            get {
                return ResourceManager.GetString("MoreOneSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is in several sketch templates.
        /// </summary>
        public static string MoreOneTemplate {
            get {
                return ResourceManager.GetString("MoreOneTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is already in use!.
        /// </summary>
        public static string NameIsAlreadyInUse {
            get {
                return ResourceManager.GetString("NameIsAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New sketch name:.
        /// </summary>
        public static string NewFormName {
            get {
                return ResourceManager.GetString("NewFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No subtype sketch.
        /// </summary>
        public static string NoSubtype {
            get {
                return ResourceManager.GetString("NoSubtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not found in.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rbr.FormSubtypeNumber.
        /// </summary>
        public static string ParameterSubtypeNumber {
            get {
                return ResourceManager.GetString("ParameterSubtypeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebar.
        /// </summary>
        public static string Rebar {
            get {
                return ResourceManager.GetString("Rebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rbr_A.
        /// </summary>
        public static string RebarAparam {
            get {
                return ResourceManager.GetString("RebarAparam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the image for a new sketch.
        /// </summary>
        public static string SelectImage {
            get {
                return ResourceManager.GetString("SelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @.
        /// </summary>
        public static string SpacingPrefix {
            get {
                return ResourceManager.GetString("SpacingPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch library editor. Version.
        /// </summary>
        public static string TitleSketchConstructor {
            get {
                return ResourceManager.GetString("TitleSketchConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sketch schedule.
        /// </summary>
        public static string TransactionRebarSketch {
            get {
                return ResourceManager.GetString("TransactionRebarSketch", resourceCulture);
            }
        }
    }
}
